#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_rating_new:
  path: rating/new/{rating}/{idArticle}
  controller: App\Controller\RatingController::new
app_article_names:
  path: article/show/names
  controller: App\Controller\ArticleController::names
